#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVMS_API
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TVMS")]
	public partial class TVMS_dataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public TVMS_dataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TVMSCon"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TVMS_dataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TVMS_dataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TVMS_dataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TVMS_dataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vw_User_n_FTP_det> vw_User_n_FTP_dets
		{
			get
			{
				return this.GetTable<vw_User_n_FTP_det>();
			}
		}
		
		public System.Data.Linq.Table<tblDeviceDetail> tblDeviceDetails
		{
			get
			{
				return this.GetTable<tblDeviceDetail>();
			}
		}
		
		public System.Data.Linq.Table<tblVoilation> tblVoilations
		{
			get
			{
				return this.GetTable<tblVoilation>();
			}
		}
		
		public System.Data.Linq.Table<vw_SearchViolation> vw_SearchViolations
		{
			get
			{
				return this.GetTable<vw_SearchViolation>();
			}
		}
		
		public System.Data.Linq.Table<tblUserMaster> tblUserMasters
		{
			get
			{
				return this.GetTable<tblUserMaster>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_User_n_FTP_det")]
	public partial class vw_User_n_FTP_det
	{
		
		private System.Nullable<decimal> _UserId;
		
		private string _LoginId;
		
		private string _Password;
		
		private string _UserType;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _PhoneNumber;
		
		private string _FtpURL;
		
		private string _FtpPort;
		
		private string _FtpUsername;
		
		private string _FtpPassword;
		
		private System.Nullable<System.DateTime> _FtpCreationDate;
		
		public vw_User_n_FTP_det()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginId", DbType="VarChar(50)")]
		public string LoginId
		{
			get
			{
				return this._LoginId;
			}
			set
			{
				if ((this._LoginId != value))
				{
					this._LoginId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="VarChar(10)")]
		public string UserType
		{
			get
			{
				return this._UserType;
			}
			set
			{
				if ((this._UserType != value))
				{
					this._UserType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(150)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(150)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="VarChar(50)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this._PhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FtpURL", DbType="VarChar(MAX)")]
		public string FtpURL
		{
			get
			{
				return this._FtpURL;
			}
			set
			{
				if ((this._FtpURL != value))
				{
					this._FtpURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FtpPort", DbType="VarChar(50)")]
		public string FtpPort
		{
			get
			{
				return this._FtpPort;
			}
			set
			{
				if ((this._FtpPort != value))
				{
					this._FtpPort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FtpUsername", DbType="VarChar(50)")]
		public string FtpUsername
		{
			get
			{
				return this._FtpUsername;
			}
			set
			{
				if ((this._FtpUsername != value))
				{
					this._FtpUsername = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FtpPassword", DbType="VarChar(50)")]
		public string FtpPassword
		{
			get
			{
				return this._FtpPassword;
			}
			set
			{
				if ((this._FtpPassword != value))
				{
					this._FtpPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FtpCreationDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FtpCreationDate
		{
			get
			{
				return this._FtpCreationDate;
			}
			set
			{
				if ((this._FtpCreationDate != value))
				{
					this._FtpCreationDate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDeviceDetails")]
	public partial class tblDeviceDetail
	{
		
		private System.Nullable<decimal> _DeviceId;
		
		private string _DeviceIMEI;
		
		private System.Nullable<char> _Status;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		public tblDeviceDetail()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceId", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DeviceId
		{
			get
			{
				return this._DeviceId;
			}
			set
			{
				if ((this._DeviceId != value))
				{
					this._DeviceId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceIMEI", DbType="VarChar(MAX)")]
		public string DeviceIMEI
		{
			get
			{
				return this._DeviceIMEI;
			}
			set
			{
				if ((this._DeviceIMEI != value))
				{
					this._DeviceIMEI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Char(1)")]
		public System.Nullable<char> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this._CreatedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this._UpdatedOn = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblVoilations")]
	public partial class tblVoilation
	{
		
		private System.Nullable<decimal> _UserId;
		
		private string _VideoFileName;
		
		private string _PicFileName;
		
		private string _LocationName;
		
		private string _Longitude;
		
		private string _Latitude;
		
		private System.Nullable<decimal> _DeviceId;
		
		private System.Nullable<char> _IsProcessed;
		
		private System.Nullable<System.DateTime> _ProcessedOn;
		
		private System.Nullable<decimal> _OffenceId;
		
		private string _VehicleNumber;
		
		private System.Nullable<char> _IsNotified;
		
		private System.Nullable<System.DateTime> _NotifiedOn;
		
		private System.Nullable<decimal> _NotifiedBy;
		
		private string _NotifiedImage;
		
		private System.Nullable<char> _IsEnforced;
		
		private System.Nullable<System.DateTime> _EnforcedOn;
		
		private string _EnforcedImage;
		
		private System.Nullable<char> _PenaltyPaid;
		
		private System.Nullable<System.DateTime> _PenaltyPaidOn;
		
		private string _PenaltyTxnNo;
		
		private string _TicketNo;
		
		private System.Nullable<System.DateTime> _VideoDateTime;
		
		public tblVoilation()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoFileName", DbType="VarChar(MAX)")]
		public string VideoFileName
		{
			get
			{
				return this._VideoFileName;
			}
			set
			{
				if ((this._VideoFileName != value))
				{
					this._VideoFileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicFileName", DbType="VarChar(MAX)")]
		public string PicFileName
		{
			get
			{
				return this._PicFileName;
			}
			set
			{
				if ((this._PicFileName != value))
				{
					this._PicFileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationName", DbType="VarChar(MAX)")]
		public string LocationName
		{
			get
			{
				return this._LocationName;
			}
			set
			{
				if ((this._LocationName != value))
				{
					this._LocationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="VarChar(200)")]
		public string Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this._Longitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="VarChar(200)")]
		public string Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this._Latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceId", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DeviceId
		{
			get
			{
				return this._DeviceId;
			}
			set
			{
				if ((this._DeviceId != value))
				{
					this._DeviceId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsProcessed", DbType="Char(1)")]
		public System.Nullable<char> IsProcessed
		{
			get
			{
				return this._IsProcessed;
			}
			set
			{
				if ((this._IsProcessed != value))
				{
					this._IsProcessed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ProcessedOn
		{
			get
			{
				return this._ProcessedOn;
			}
			set
			{
				if ((this._ProcessedOn != value))
				{
					this._ProcessedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OffenceId", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> OffenceId
		{
			get
			{
				return this._OffenceId;
			}
			set
			{
				if ((this._OffenceId != value))
				{
					this._OffenceId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleNumber", DbType="VarChar(200)")]
		public string VehicleNumber
		{
			get
			{
				return this._VehicleNumber;
			}
			set
			{
				if ((this._VehicleNumber != value))
				{
					this._VehicleNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsNotified", DbType="Char(1)")]
		public System.Nullable<char> IsNotified
		{
			get
			{
				return this._IsNotified;
			}
			set
			{
				if ((this._IsNotified != value))
				{
					this._IsNotified = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotifiedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> NotifiedOn
		{
			get
			{
				return this._NotifiedOn;
			}
			set
			{
				if ((this._NotifiedOn != value))
				{
					this._NotifiedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotifiedBy", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> NotifiedBy
		{
			get
			{
				return this._NotifiedBy;
			}
			set
			{
				if ((this._NotifiedBy != value))
				{
					this._NotifiedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotifiedImage", DbType="VarChar(MAX)")]
		public string NotifiedImage
		{
			get
			{
				return this._NotifiedImage;
			}
			set
			{
				if ((this._NotifiedImage != value))
				{
					this._NotifiedImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsEnforced", DbType="Char(1)")]
		public System.Nullable<char> IsEnforced
		{
			get
			{
				return this._IsEnforced;
			}
			set
			{
				if ((this._IsEnforced != value))
				{
					this._IsEnforced = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnforcedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> EnforcedOn
		{
			get
			{
				return this._EnforcedOn;
			}
			set
			{
				if ((this._EnforcedOn != value))
				{
					this._EnforcedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnforcedImage", DbType="VarChar(MAX)")]
		public string EnforcedImage
		{
			get
			{
				return this._EnforcedImage;
			}
			set
			{
				if ((this._EnforcedImage != value))
				{
					this._EnforcedImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PenaltyPaid", DbType="Char(1)")]
		public System.Nullable<char> PenaltyPaid
		{
			get
			{
				return this._PenaltyPaid;
			}
			set
			{
				if ((this._PenaltyPaid != value))
				{
					this._PenaltyPaid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PenaltyPaidOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> PenaltyPaidOn
		{
			get
			{
				return this._PenaltyPaidOn;
			}
			set
			{
				if ((this._PenaltyPaidOn != value))
				{
					this._PenaltyPaidOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PenaltyTxnNo", DbType="VarChar(MAX)")]
		public string PenaltyTxnNo
		{
			get
			{
				return this._PenaltyTxnNo;
			}
			set
			{
				if ((this._PenaltyTxnNo != value))
				{
					this._PenaltyTxnNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TicketNo", DbType="VarChar(MAX)")]
		public string TicketNo
		{
			get
			{
				return this._TicketNo;
			}
			set
			{
				if ((this._TicketNo != value))
				{
					this._TicketNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> VideoDateTime
		{
			get
			{
				return this._VideoDateTime;
			}
			set
			{
				if ((this._VideoDateTime != value))
				{
					this._VideoDateTime = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_SearchViolations")]
	public partial class vw_SearchViolation
	{
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _LoginId;
		
		private string _VideoFileName;
		
		private string _PicFileName;
		
		private string _LocationName;
		
		private string _Longitude;
		
		private string _Latitude;
		
		private string _DeviceIMEI;
		
		private System.Nullable<char> _IsProcessed;
		
		private System.Nullable<System.DateTime> _ProcessedOn;
		
		private string _VehicleNumber;
		
		private string _TicketNo;
		
		private System.Nullable<System.DateTime> _VideoDateTime;
		
		private string _OffenceName;
		
		private System.Nullable<decimal> _Penalty;
		
		private System.Nullable<decimal> _UserId;
		
		public vw_SearchViolation()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(150)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(150)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginId", DbType="VarChar(50)")]
		public string LoginId
		{
			get
			{
				return this._LoginId;
			}
			set
			{
				if ((this._LoginId != value))
				{
					this._LoginId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoFileName", DbType="VarChar(MAX)")]
		public string VideoFileName
		{
			get
			{
				return this._VideoFileName;
			}
			set
			{
				if ((this._VideoFileName != value))
				{
					this._VideoFileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicFileName", DbType="VarChar(MAX)")]
		public string PicFileName
		{
			get
			{
				return this._PicFileName;
			}
			set
			{
				if ((this._PicFileName != value))
				{
					this._PicFileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationName", DbType="VarChar(MAX)")]
		public string LocationName
		{
			get
			{
				return this._LocationName;
			}
			set
			{
				if ((this._LocationName != value))
				{
					this._LocationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="VarChar(200)")]
		public string Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this._Longitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="VarChar(200)")]
		public string Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this._Latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceIMEI", DbType="VarChar(MAX)")]
		public string DeviceIMEI
		{
			get
			{
				return this._DeviceIMEI;
			}
			set
			{
				if ((this._DeviceIMEI != value))
				{
					this._DeviceIMEI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsProcessed", DbType="Char(1)")]
		public System.Nullable<char> IsProcessed
		{
			get
			{
				return this._IsProcessed;
			}
			set
			{
				if ((this._IsProcessed != value))
				{
					this._IsProcessed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ProcessedOn
		{
			get
			{
				return this._ProcessedOn;
			}
			set
			{
				if ((this._ProcessedOn != value))
				{
					this._ProcessedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleNumber", DbType="VarChar(200)")]
		public string VehicleNumber
		{
			get
			{
				return this._VehicleNumber;
			}
			set
			{
				if ((this._VehicleNumber != value))
				{
					this._VehicleNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TicketNo", DbType="VarChar(MAX)")]
		public string TicketNo
		{
			get
			{
				return this._TicketNo;
			}
			set
			{
				if ((this._TicketNo != value))
				{
					this._TicketNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> VideoDateTime
		{
			get
			{
				return this._VideoDateTime;
			}
			set
			{
				if ((this._VideoDateTime != value))
				{
					this._VideoDateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OffenceName", DbType="VarChar(MAX)")]
		public string OffenceName
		{
			get
			{
				return this._OffenceName;
			}
			set
			{
				if ((this._OffenceName != value))
				{
					this._OffenceName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Penalty", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Penalty
		{
			get
			{
				return this._Penalty;
			}
			set
			{
				if ((this._Penalty != value))
				{
					this._Penalty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUserMaster")]
	public partial class tblUserMaster
	{
		
		private System.Nullable<decimal> _UserId;
		
		private string _LoginId;
		
		private string _Password;
		
		private string _UserType;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _PhoneNumber;
		
		private System.Nullable<decimal> _FtpId;
		
		public tblUserMaster()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginId", DbType="VarChar(50)")]
		public string LoginId
		{
			get
			{
				return this._LoginId;
			}
			set
			{
				if ((this._LoginId != value))
				{
					this._LoginId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="VarChar(10)")]
		public string UserType
		{
			get
			{
				return this._UserType;
			}
			set
			{
				if ((this._UserType != value))
				{
					this._UserType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(150)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(150)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="VarChar(50)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this._PhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FtpId", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> FtpId
		{
			get
			{
				return this._FtpId;
			}
			set
			{
				if ((this._FtpId != value))
				{
					this._FtpId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
